# Generated by Django 4.0.4 on 2022-06-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_agegroup_image_cateogry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroup',
            old_name='Name',
            new_name='child_name',
        ),
        migrations.RenameField(
            model_name='cateogry',
            old_name='Name',
            new_name='group_name',
        ),
    ]
