# Generated by Django 4.0.4 on 2022-06-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_agegroup_child_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='cateogry',
        ),
        migrations.DeleteModel(
            name='cateogry',
        ),
    ]
