# Generated by Django 4.0.4 on 2022-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_agegroup_cateogry_delete_cateogry'),
    ]

    operations = [
        migrations.CreateModel(
            name='newboarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pic/images')),
                ('taught', models.TextField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('Hobby', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='agegroup',
        ),
    ]
