# Generated by Django 4.0.4 on 2022-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_age_11_15_age_16_18_age_3_5_age_6_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newboarn',
            name='Hobby',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
