# Generated by Django 4.0.4 on 2022-06-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_contactme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gateway',
            new_name='money',
        ),
    ]
