# Generated by Django 4.0.4 on 2022-06-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_contactme2_detail_donatebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Donatebox',
            field=models.CharField(max_length=50),
        ),
    ]
