# Generated by Django 4.0.4 on 2022-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_detail_donateitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='donateanything',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Donatebox', models.CharField(max_length=50)),
            ],
        ),
    ]
