# Generated by Django 4.0.4 on 2022-06-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_donateanything'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donateitems',
        ),
    ]
