# Generated by Django 4.0.4 on 2022-06-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_delete_donateitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='summerdonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Donatebox', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='winterdonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Donatebox', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='summerd',
        ),
        migrations.DeleteModel(
            name='winterd',
        ),
        migrations.AlterField(
            model_name='donateanything',
            name='Donatebox',
            field=models.CharField(max_length=500),
        ),
    ]
