# Generated by Django 4.0.4 on 2022-06-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='Cpassword',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='Password',
            field=models.CharField(max_length=150),
        ),
    ]
