# Generated by Django 4.0.4 on 2022-07-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_summercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summercontact',
            name='Email_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='summercontact',
            name='Phoneno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='summercontact',
            name='Pincode',
            field=models.CharField(max_length=50),
        ),
    ]
