# Generated by Django 4.0.4 on 2022-07-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_summerdonate_delete_summercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneydonateone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('cardno', models.IntegerField()),
                ('expire', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='moneydonate',
        ),
    ]
