# Generated by Django 4.0.4 on 2022-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_moneydonate_delete_moneydonateone'),
    ]

    operations = [
        migrations.CreateModel(
            name='donatemoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('Donatebox', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='moneydonate',
        ),
    ]
