# Generated by Django 4.0.4 on 2022-07-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_summerdonate_donatebox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summerdonate',
            old_name='City',
            new_name='Card_no',
        ),
        migrations.RenameField(
            model_name='summerdonate',
            old_name='State',
            new_name='Cvv',
        ),
        migrations.RenameField(
            model_name='summerdonate',
            old_name='Pin',
            new_name='Exp',
        ),
    ]
