# Generated by Django 4.0.4 on 2022-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_city_summerdonate_card_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneydonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Card_no', models.CharField(max_length=50)),
                ('Exp', models.IntegerField()),
                ('Cvv', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Summerdonate',
        ),
    ]
