# Generated by Django 4.0.4 on 2022-07-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_sign_delete_sign_uppartner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign',
        ),
    ]
