# Generated by Django 4.0.4 on 2022-07-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_partnersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnersignupform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('Conform_password', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='partnersignup',
        ),
    ]
