# Generated by Django 4.0.4 on 2022-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='partner',
            new_name='partnerdone',
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('PAN', 'pan'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('Passport', 'passport')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Married', 'married'), ('Widow', 'widow'), ('Divorcee', 'divorcee'), ('Single', 'single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('PAN', 'pan'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('Passport', 'passport')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
    ]
