# Generated by Django 4.0.4 on 2022-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_rename_partner_partnerdone_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerdone',
            old_name='Password',
            new_name='Purpose',
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('voter', 'voter'), ('PAN', 'pan'), ('Passport', 'passport'), ('Aadhar', 'aadhar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('voter', 'voter'), ('PAN', 'pan'), ('Passport', 'passport'), ('Aadhar', 'aadhar')], max_length=10),
        ),
    ]
