# Generated by Django 4.0.4 on 2022-07-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_rename_password_partnerdone_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('Aadhar', 'aadhar'), ('Passport', 'passport'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Married', 'married'), ('Single', 'single'), ('Divorcee', 'divorcee'), ('Widow', 'widow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('Aadhar', 'aadhar'), ('Passport', 'passport'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
    ]
