# Generated by Django 4.0.4 on 2022-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_delete_givemoney_delete_partnerreg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=80)),
                ('Phone', models.IntegerField()),
                ('Purpose', models.CharField(max_length=80)),
                ('Date', models.DateField()),
                ('Image', models.ImageField(default='', upload_to='upload_pic/images')),
            ],
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Divorcee', 'divorcee'), ('Single', 'single'), ('Married', 'married'), ('Widow', 'widow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
    ]
