# Generated by Django 4.0.4 on 2022-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_booking_table_alter_adoptform_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='booking_table',
            name='Phone',
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('voter', 'voter'), ('Passport', 'passport'), ('Aadhar', 'aadhar'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Widow', 'widow'), ('Married', 'married'), ('Single', 'single'), ('Divorcee', 'divorcee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('voter', 'voter'), ('Passport', 'passport'), ('Aadhar', 'aadhar'), ('PAN', 'pan')], max_length=10),
        ),
    ]
