# Generated by Django 4.0.4 on 2022-07-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_remove_booking_table_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('Aadhar', 'aadhar'), ('Passport', 'passport'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Widow', 'widow'), ('Divorcee', 'divorcee'), ('Married', 'married'), ('Single', 'single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('Aadhar', 'aadhar'), ('Passport', 'passport'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='Date',
            field=models.CharField(max_length=90),
        ),
    ]
