# Generated by Django 4.0.4 on 2022-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_adoptform_category_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('PAN', 'pan'), ('Aadhar', 'aadhar'), ('voter', 'voter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Divorcee', 'divorcee'), ('Widow', 'widow'), ('Married', 'married'), ('Single', 'single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('PAN', 'pan'), ('Aadhar', 'aadhar'), ('voter', 'voter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
    ]
