# Generated by Django 4.0.4 on 2022-07-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_adoptform_category_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adoptform',
        ),
    ]
