# Generated by Django 4.0.4 on 2022-07-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_delete_adoptform'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent_adopted_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Aadhar', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(max_length=30)),
                ('Biological_Childrens', models.IntegerField(max_length=30)),
                ('Adopted_Children', models.IntegerField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pincode', models.IntegerField()),
            ],
        ),
    ]
