# Generated by Django 4.0.4 on 2022-07-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_alter_parent_adopted_form_adopted_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_adopted_form',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
