# Generated by Django 4.0.4 on 2022-06-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_newboarn_delete_agegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_11_15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pic/images')),
                ('taught', models.TextField(max_length=200)),
                ('age', models.CharField(max_length=15)),
                ('Hobby', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='age_16_18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pic/images')),
                ('taught', models.TextField(max_length=200)),
                ('age', models.CharField(max_length=15)),
                ('Hobby', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='age_3_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pic/images')),
                ('taught', models.TextField(max_length=200)),
                ('age', models.CharField(max_length=15)),
                ('Hobby', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='age_6_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pic/images')),
                ('taught', models.TextField(max_length=200)),
                ('age', models.CharField(max_length=15)),
                ('Hobby', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='newboarn',
            name='age',
            field=models.CharField(max_length=15),
        ),
    ]
