# Generated by Django 4.0.4 on 2022-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_address_contactme_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Last_name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Cradname', models.CharField(max_length=50)),
                ('Cardno', models.IntegerField()),
                ('Expireyear', models.CharField(max_length=50)),
                ('Expiremonth', models.CharField(max_length=50)),
                ('Cvv', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactme',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
