# Generated by Django 4.0.4 on 2022-06-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_cradname_gateway_cardname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='Cardname',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Cardno',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Cvv',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Expiremonth',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Expireyear',
        ),
    ]
