# Generated by Django 4.0.4 on 2022-06-20 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_gateway_cardname_remove_gateway_cardno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactme',
        ),
    ]
