# Generated by Django 4.0.4 on 2022-06-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_moneyc_moneydonate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='Pin',
            new_name='Amount',
        ),
        migrations.RemoveField(
            model_name='money',
            name='City',
        ),
        migrations.RemoveField(
            model_name='money',
            name='State',
        ),
    ]
