# Generated by Django 4.0.4 on 2022-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_winterd'),
    ]

    operations = [
        migrations.CreateModel(
            name='summerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
            ],
        ),
    ]
