# Generated by Django 4.0.4 on 2022-06-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_summerdonation_winterdonation_delete_summerd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Password', models.IntegerField()),
                ('Cpassword', models.IntegerField()),
            ],
        ),
    ]
