# Generated by Django 4.0.4 on 2022-07-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_sign_up_cpassword_alter_sign_up_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='summerdonation',
        ),
    ]
