# Generated by Django 4.0.4 on 2022-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_summerdonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Phoneno', models.IntegerField()),
                ('Cityname', models.CharField(max_length=50)),
                ('Statename', models.CharField(max_length=60)),
                ('Pincode', models.IntegerField()),
                ('Donate', models.CharField(max_length=200)),
            ],
        ),
    ]
