# Generated by Django 4.0.4 on 2022-07-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_partnerdnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
            ],
        ),
    ]
