# Generated by Django 4.0.4 on 2022-06-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_newboarn_hobby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='age_6_10',
            new_name='age_11_15y',
        ),
        migrations.RenameModel(
            old_name='age_16_18',
            new_name='age_16_18y',
        ),
        migrations.RenameModel(
            old_name='age_3_5',
            new_name='age_3_5y',
        ),
        migrations.RenameModel(
            old_name='age_11_15',
            new_name='age_6_10y',
        ),
    ]
