# Generated by Django 4.0.4 on 2022-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactme_alter_age_11_15y_hobby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactme',
            old_name='Address',
            new_name='Message',
        ),
    ]
