# Generated by Django 4.0.4 on 2022-06-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_gateway_alter_contactme_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='Cradname',
            new_name='Cardname',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='Last_name',
        ),
    ]
