# Generated by Django 4.0.4 on 2022-06-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_moneyc_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='moneyc',
            new_name='moneydonate',
        ),
    ]
