# Generated by Django 4.0.4 on 2022-06-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_pin_money_amount_remove_money_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='Amount',
            new_name='Pin',
        ),
    ]
