# Generated by Django 4.0.4 on 2022-06-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_detail_donatebox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='donateitems',
        ),
    ]
