# Generated by Django 4.0.4 on 2022-07-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_moneydonateone_delete_moneydonate'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_uppartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=150)),
                ('Cpassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
