# Generated by Django 4.0.4 on 2022-07-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_givemoney_delete_donatemoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summerdonate',
            name='Donatebox',
        ),
    ]
