# Generated by Django 4.0.4 on 2022-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_moneydonate_delete_summerdonate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneydonate',
            name='Exp',
            field=models.CharField(max_length=50),
        ),
    ]
