# Generated by Django 4.0.4 on 2022-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_rename_conform_password_partnersignup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_Name', models.CharField(max_length=80)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('Category', models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10)),
                ('Document', models.CharField(choices=[('Passport', 'passport'), ('PAN', 'pan'), ('voter', 'voter'), ('Aadhar', 'aadhar')], max_length=10)),
                ('ID_NO', models.CharField(max_length=80)),
                ('Email_ID', models.CharField(max_length=80)),
                ('Phone', models.CharField(max_length=80)),
                ('Martital_Status', models.CharField(choices=[('Single', 'single'), ('Widow', 'widow'), ('Married', 'married'), ('Divorcee', 'divorcee')], max_length=10)),
                ('Spouse_name', models.CharField(max_length=80)),
                ('Spouse_DOB', models.CharField(max_length=80)),
                ('Spouse_Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10)),
                ('Spouse_Category', models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10)),
                ('Spouse_Document', models.CharField(choices=[('Passport', 'passport'), ('PAN', 'pan'), ('voter', 'voter'), ('Aadhar', 'aadhar')], max_length=10)),
                ('Spouse_ID_NO', models.CharField(max_length=80)),
                ('Spouse_Email_ID', models.CharField(max_length=80)),
                ('Spouse_Phone', models.CharField(max_length=80)),
                ('Biological_children', models.IntegerField()),
                ('Adopted_children', models.IntegerField()),
                ('Address', models.CharField(max_length=80)),
                ('District', models.CharField(max_length=80)),
                ('State', models.CharField(max_length=80)),
                ('Pin_code', models.IntegerField()),
                ('Current_Address', models.CharField(max_length=80)),
                ('Current_District', models.CharField(max_length=80)),
                ('Current_State', models.CharField(max_length=80)),
                ('Current_Pin_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='partnerdnt',
        ),
    ]
