# Generated by Django 4.0.4 on 2022-07-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_adoptform_category_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Purpose', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='partnerdone',
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Married', 'married'), ('Widow', 'widow'), ('Single', 'single'), ('Divorcee', 'divorcee')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Nri', 'nri'), ('Indian', 'indian')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10),
        ),
    ]
