# Generated by Django 4.0.4 on 2022-07-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_partnerreg_delete_partnerdone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptform',
            name='Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('voter', 'voter'), ('PAN', 'pan'), ('Aadhar', 'aadhar'), ('Passport', 'passport')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Divorcee', 'divorcee'), ('Widow', 'widow'), ('Single', 'single'), ('Married', 'married')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Category',
            field=models.CharField(choices=[('Indian', 'indian'), ('Nri', 'nri')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('voter', 'voter'), ('PAN', 'pan'), ('Aadhar', 'aadhar'), ('Passport', 'passport')], max_length=10),
        ),
    ]
