# Generated by Django 4.0.4 on 2022-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_adoptform_category_alter_adoptform_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptform',
            name='Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Martital_Status',
            field=models.CharField(choices=[('Single', 'single'), ('Married', 'married'), ('Divorcee', 'divorcee'), ('Widow', 'widow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Document',
            field=models.CharField(choices=[('Passport', 'passport'), ('Aadhar', 'aadhar'), ('voter', 'voter'), ('PAN', 'pan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptform',
            name='Spouse_Gender',
            field=models.CharField(choices=[('Female', 'female'), ('Male', 'male')], max_length=10),
        ),
    ]
